version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: filter_db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: password
      MYSQL_USER: sammy
    ports:
      - "3306:3306"